export const route = {
  BACKUP_MNEMONIC_SCREEN: 'BackUpMnemonic',
  ENTER_MNEMONIC_SCREEN: 'EnterMnemonic',
  SPLASH_SCREEN: 'Splash',
  AUTHORIZE_PINCODE_SCREEN: 'AuthorizePinCode',
  CREATE_PINCODE_SCREEN: 'CreatePinCode',
  INITIAL_SCREEN: 'Initial',
  MAIN_SCREEN: 'Main',
  ETHEREUM_ROUTE: 'ETH',
  BITCOIN_ROUTE: 'BTC',
  SELECT_ADDRESS_SCREEN: 'SelectAddress',
  TOKEN_SEND_SCREEN: 'TokenSend',
  TOKEN_RECEIVE_SCREEN: 'TokenReceive',
  SUMMARY_TX_ROUTE: 'SummaryTx',
  TOKEN_DETAIL_SCREEN: 'TokenDetail',
  DETAIL_TX_ROUTE: 'DetailTx',
  ADD_SOMETHING_SCREEN: 'AddSomething',
  ADDRESS_LIST_SCREEN: 'AddressList',
  MANAGING_SCREEN: 'Managing',
  MANAGE_WALLET_ROUTE: 'ManageWallet',
  BACKUP_OR_DELETE_ROUTE: 'BackUpOrDelete',
  BACKUP_QR_SCREEN: 'BackUpQRCode',
  DELETE_WALLET_SCREEN: 'DeleteWallet',
  SETTING_SCREEN: 'Setting',
};
